Legger til tjenestebokser for midlertidig og varig lønnstilskudd
navikt/ditt-nav-arbeidsgiver pull request #229
Opened 2020-08-31 13:21 UTC by Oslove

2020-09-03 11:51 UTC, peterbb approved these changes
Ser fint ut synes jeg :)

2020-09-04 08:04 UTC, hildeheggstad commented on src/App/Hovedside/BeOmTilgang/finnManglendeTilgangOgGenererBokserFunksjoner.ts
> +    valgtOrgNr: string
er du sikker på at denne alltids er definert? hva om man bare har tilgang til syfo?

2020-09-04 08:14 UTC, hildeheggstad requested changes

2020-09-04 08:14 UTC, hildeheggstad commented on src/mock/altinnMock.ts
> +fetchMock
mockobjektet skal kanskje ikke hete arbeidsforholdRespons her? :)

2020-09-04 10:23 UTC, Oslove commented on src/mock/altinnMock.ts
> +fetchMock
Godt poeng :) Jeg har endret litt nå slik at de fleste kall til "rettigheter" får det som nå heter "rettigheterSkjemaDefaultResponse"

2020-09-04 10:45 UTC, merged